import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	platform: "node",
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
		...builtinModules.map((m) => `node:${m}`)],
	// Replace process.env.NODE_ENV at build time so esbuild can tree-shake the
	// development-only builds of React/React-DOM (and other deps) out of the
	// production bundle. This removes the dev React-DOM build entirely, which
	// also strips the dynamic <script> element creations that live in it, and
	// significantly reduces the shipped bundle size.
	define: {
		"process.env.NODE_ENV": JSON.stringify(prod ? "production" : "development"),
	},
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	jsxFactory: "React.createElement",
	jsxFragment: "React.Fragment",
	loader: {
		".ts": "ts",
		".tsx": "tsx",
		".css": "css"
	  }
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
