import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Normalise a path for cross-platform (Windows-insensitive) comparison.
const normalizePath = (p) => resolve(p).replace(/\\/g, "/").toLowerCase();

// Resolve langsmith's `browser` field so we can swap its Node-only modules
// (fs, worker_threads) for the browser stubs the package itself ships. esbuild
// does not honour the `browser` field while `platform: "node"` is set, so we do
// it explicitly. This keeps the bundle from ever touching the Node `fs` /
// `worker_threads` builtins — Obsidian rejects plugins that access the
// filesystem outside the vault API.
const langsmithRoot = resolve(process.cwd(), "node_modules/langsmith");
const langsmithBrowserMap = JSON.parse(
	readFileSync(resolve(langsmithRoot, "package.json"), "utf8")
).browser ?? {};
const langsmithSwaps = Object.entries(langsmithBrowserMap).map(([from, to]) => ({
	from: normalizePath(resolve(langsmithRoot, from)),
	to: resolve(langsmithRoot, to),
}));

// esbuild plugin that hardens third-party dependencies so the bundle complies
// with Obsidian's plugin security guidelines.
const obsidianSecurityHardening = {
	name: "obsidian-security-hardening",
	setup(build) {
		// 1. Swap langsmith's Node-only modules for their browser stubs.
		build.onLoad({ filter: /langsmith[\\/]dist[\\/]/ }, (args) => {
			const swap = langsmithSwaps.find((s) => s.from === normalizePath(args.path));
			if (!swap) return null;
			return { contents: readFileSync(swap.to, "utf8"), loader: "js" };
		});

		// 2. Neutralise React DOM's resource-hoisting feature, which dynamically
		// creates <script> elements (ReactDOM.preinit / preinitModule / hoistable
		// <script> resources). This plugin never uses that feature, and Obsidian
		// flags any dynamic <script> creation as a security risk. Swapping the tag
		// for an inert <template> removes the flagged pattern and guarantees these
		// dead code paths can never inject executable scripts.
		build.onLoad({ filter: /react-dom-client\.(production|development)\.js$/ }, (args) => {
			const patched = readFileSync(args.path, "utf8")
				// preinit / preinitModule / hoistable <script> resources.
				.replaceAll('createElement("script")', 'createElement("template")')
				// Host-element renderer path for a literal <script> tag in the React
				// tree: it builds an (inert, non-executing) <script> node via innerHTML.
				// Swap it for a <template> so no <script> node is ever produced.
				.replaceAll('"<script>\\x3c/script>"', '"<template>\\x3c/template>"');
			return { contents: patched, loader: "js" };
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	plugins: [obsidianSecurityHardening],
	entryPoints: ["src/main.ts"],
	bundle: true,
	platform: "node",
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
		...builtinModules.map((m) => `node:${m}`)],
	// Replace process.env.NODE_ENV at build time so esbuild can tree-shake the
	// development-only builds of React/React-DOM (and other deps) out of the
	// production bundle, significantly reducing the shipped bundle size.
	// (the dynamic <script> creations React DOM ships are neutralised separately
	// by the obsidianSecurityHardening plugin above.)
	define: {
		"process.env.NODE_ENV": JSON.stringify(prod ? "production" : "development"),
	},
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	jsxFactory: "React.createElement",
	jsxFragment: "React.Fragment",
	loader: {
		".ts": "ts",
		".tsx": "tsx",
		".css": "css"
	  }
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
